!function(){let t={fcp:null,lcp:null,cls:0,clsEntries:[],longTasks:0,longTasksTime:0,totalBlockingTime:0,resources:[],totalRequests:0,totalBytes:0,nav:null},e=t=>null==t?"-":t.toFixed(0)+" ms",i=t=>null==t?"-":(t/1024).toFixed(1)+" KB";try{let o=new PerformanceObserver(e=>{for(let i of e.getEntries())"first-contentful-paint"===i.name&&null==t.fcp&&(t.fcp=i.startTime,v(),o.disconnect())});o.observe({type:"paint",buffered:!0})}catch(s){}try{let n=new PerformanceObserver(e=>{for(let i of e.getEntries())t.lcp=i.renderTime||i.loadTime||i.startTime;v()});n.observe({type:"largest-contentful-paint",buffered:!0}),addEventListener("visibilitychange",()=>{"hidden"===document.visibilityState&&n.takeRecords()})}catch(l){}try{let r=new PerformanceObserver(e=>{for(let i of e.getEntries())i.hadRecentInput||(t.cls+=i.value,t.clsEntries.push(i));v()});r.observe({type:"layout-shift",buffered:!0})}catch(d){}try{let a=new PerformanceObserver(e=>{for(let i of e.getEntries())t.longTasks++,t.longTasksTime+=i.duration,t.totalBlockingTime+=Math.max(0,i.duration-50);v()});a.observe({entryTypes:["longtask"]})}catch(p){}let c=document.createElement("div");function v(){!function e(){let i=performance.getEntriesByType("resource");t.resources=i,t.totalRequests=i.length+1;let o=0;for(let s of i){let n=s.transferSize&&s.transferSize>0?s.transferSize:s.encodedBodySize||0;o+=n}t.totalBytes=o}(),function e(){let i=performance.getEntriesByType("navigation")[0];i&&(t.nav=i)}();let o=t=>c.querySelector(t);o("#m-fcp").textContent=e(t.fcp),o("#m-lcp").textContent=e(t.lcp),o("#m-cls").textContent=t.cls?t.cls.toFixed(3):"-",o("#m-tbt").textContent=t.totalBlockingTime?e(t.totalBlockingTime):"-",o("#m-req").textContent=String(t.totalRequests||"-"),o("#m-bytes").textContent=t.totalBytes?i(t.totalBytes):"-",window.__metrics={fcp:t.fcp,lcp:t.lcp,cls:t.cls,tbtApprox:t.totalBlockingTime,totalRequests:t.totalRequests,totalBytes:t.totalBytes,navigation:t.nav}}c.setAttribute("id","perf-panel"),Object.assign(c.style,{position:"fixed",right:"16px",bottom:"16px",zIndex:9999,width:"320px",maxWidth:"90vw",fontFamily:"ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial",background:"rgba(10,12,28,.9)",color:"#E8ECF1",border:"1px solid rgba(255,255,255,.12)",borderRadius:"12px",boxShadow:"0 10px 40px rgba(0,0,0,.5)",backdropFilter:"blur(6px) saturate(120%)",padding:"12px 14px"}),c.innerHTML=`
    <div style="display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px">
      <strong style="letter-spacing:.2px">\xc9valuation perfs</strong>
      <div>
        <button id="perf-refresh" style="background:#7C5CFF;color:white;border:0;border-radius:8px;padding:6px 10px;cursor:pointer">Mesurer</button>
        <button id="perf-close" style="background:transparent;color:#c9d1d9;border:1px solid rgba(255,255,255,.2);border-radius:8px;padding:6px 8px;margin-left:6px;cursor:pointer">\xd7</button>
      </div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:13px">
      <div><div style="opacity:.8">FCP</div><div id="m-fcp" style="font-weight:600">-</div></div>
      <div><div style="opacity:.8">LCP</div><div id="m-lcp" style="font-weight:600">-</div></div>
      <div><div style="opacity:.8">CLS</div><div id="m-cls" style="font-weight:600">-</div></div>
      <div><div style="opacity:.8">TBT (≈)</div><div id="m-tbt" style="font-weight:600">-</div></div>
      <div><div style="opacity:.8">Requ\xeates</div><div id="m-req" style="font-weight:600">-</div></div>
      <div><div style="opacity:.8">Poids total</div><div id="m-bytes" style="font-weight:600">-</div></div>
    </div>
    <div style="margin-top:8px;font-size:12px;opacity:.8">
      <div id="m-note">Cliquez sur <em>Mesurer</em> apr\xe8s vos modifications.</div>
    </div>
  `,document.addEventListener("DOMContentLoaded",()=>{document.body.appendChild(c)}),document.addEventListener("click",t=>{t.target&&"perf-refresh"===t.target.id&&v(),t.target&&"perf-close"===t.target.id&&c.remove()}),addEventListener("load",()=>{})}();
